In [27]:
import pandas as pd
import re
import numpy as np

In [28]:
df = pd.read_csv('annual-number-of-deaths-by-cause.csv')

In [29]:
df.head()

,Entity,Code,Year,Number of executions (Amnesty International),Deaths - Meningitis - Sex: Both - Age: All Ages (Number),Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number),Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number),Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number),Deaths - Malaria - Sex: Both - Age: All Ages (Number),Deaths - Drowning - Sex: Both - Age: All Ages (Number),...,Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number),Deaths - Poisonings - Sex: Both - Age: All Ages (Number),Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number),Terrorism (deaths),Deaths - Road injuries - Sex: Both - Age: All Ages (Number),Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number),Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number),Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number),"Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)",Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number)
0,Afghanistan,AFG,2007,15,2933.0,1402.0,450.0,2488.0,393.0,2127.0,...,4490.0,512.0,2439.0,1199.0,7425.0,7222.0,3346.0,6458.0,481.0,3437.0
1,Afghanistan,AFG,2008,17,2731.0,1424.0,455.0,2277.0,255.0,1973.0,...,4534.0,495.0,2231.0,1092.0,7355.0,7143.0,3316.0,6408.0,462.0,3005.0
2,Afghanistan,AFG,2009,0,2460.0,1449.0,460.0,2040.0,239.0,1852.0,...,4597.0,483.0,1998.0,1065.0,7290.0,7045.0,3291.0,6358.0,448.0,2663.0
3,Afghanistan,AFG,2011,2,2327.0,1508.0,473.0,1846.0,390.0,1775.0,...,4785.0,483.0,1805.0,1525.0,7432.0,6916.0,3318.0,6370.0,448.0,2365.0
4,Afghanistan,AFG,2012,14,2254.0,1544.0,482.0,1705.0,94.0,1716.0,...,4846.0,482.0,1667.0,3521.0,7494.0,6878.0,3353.0,6398.0,445.0,2264.0

In [30]:
lst = list(df)

for i in range(len(lst)):
    e = lst[i]
    if 'Deaths -' in e:
        e = re.sub(r'Deaths - ([^-]+).*', r'\1', e )
        lst[i] = str(e)
        
lst[lst.index('Terrorism (deaths)')] = 'Terrorism'
        
df.columns = lst

df.head()

,Entity,Code,Year,Number of executions (Amnesty International),Meningitis,Alzheimer's disease and other dementias,Parkinson's disease,Nutritional deficiencies,Malaria,Drowning,...,Chronic kidney disease,Poisonings,Protein,Terrorism,Road injuries,Chronic respiratory diseases,Cirrhosis and other chronic liver diseases,Digestive diseases,"Fire, heat, and hot substances",Acute hepatitis
0,Afghanistan,AFG,2007,15,2933.0,1402.0,450.0,2488.0,393.0,2127.0,...,4490.0,512.0,2439.0,1199.0,7425.0,7222.0,3346.0,6458.0,481.0,3437.0
1,Afghanistan,AFG,2008,17,2731.0,1424.0,455.0,2277.0,255.0,1973.0,...,4534.0,495.0,2231.0,1092.0,7355.0,7143.0,3316.0,6408.0,462.0,3005.0
2,Afghanistan,AFG,2009,0,2460.0,1449.0,460.0,2040.0,239.0,1852.0,...,4597.0,483.0,1998.0,1065.0,7290.0,7045.0,3291.0,6358.0,448.0,2663.0
3,Afghanistan,AFG,2011,2,2327.0,1508.0,473.0,1846.0,390.0,1775.0,...,4785.0,483.0,1805.0,1525.0,7432.0,6916.0,3318.0,6370.0,448.0,2365.0
4,Afghanistan,AFG,2012,14,2254.0,1544.0,482.0,1705.0,94.0,1716.0,...,4846.0,482.0,1667.0,3521.0,7494.0,6878.0,3353.0,6398.0,445.0,2264.0

In [36]:
df[df.Entity == 'United States'].sort_values('Year')['Cardiovascular diseases ']

6714    879646.0
6715    877798.0
6716    874992.0
6717    895086.0
6718    899691.0
6719    908922.0
6720    907009.0
6721    904335.0
6722    909266.0
6723    920654.0
6724    918346.0
6725    913252.0
6726    908753.0
6727    895284.0
6728    868245.0
6729    864804.0
6730    850549.0
6704    836120.0
6705    833165.0
6706    823362.0
6707    820215.0
6708    830800.0
6709    837102.0
6710    847344.0
6711    858443.0
6712    876853.0
6713    892268.0
6731    899212.0
6732    929375.0
6733    957455.0
Name: Cardiovascular diseases , dtype: float64

In [12]:
df.to_csv('second.csv')

In [17]:
df = df.drop(['Year'], axis=1)

KeyError: "['Year'] not found in axis"

In [18]:
df = df.groupby(['Entity', 'Code']).sum().reset_index()
df

/tmp/ipykernel_67983/1671593923.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = df.groupby(['Entity', 'Code']).sum().reset_index()

,Entity,Code,Deaths - Meningitis - Sex: Both - Age: All Ages (Number),Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number),Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number),Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number),Deaths - Malaria - Sex: Both - Age: All Ages (Number),Deaths - Drowning - Sex: Both - Age: All Ages (Number),Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number),Deaths - Maternal disorders - Sex: Both - Age: All Ages (Number),...,Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number),Deaths - Poisonings - Sex: Both - Age: All Ages (Number),Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number),Terrorism (deaths),Deaths - Road injuries - Sex: Both - Age: All Ages (Number),Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number),Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number),Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number),"Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)",Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number)
0,Afghanistan,AFG,78666.0,41998.0,13397.0,71453.0,13924.0,56536.0,108228.0,129621.0,...,134676.0,14530.0,70163.0,39193.0,208331.0,209857.0,98419.0,186959.0,13559.0,98108.0
1,Albania,ALB,1323.0,16549.0,4491.0,569.0,0.0,2397.0,5242.0,246.0,...,7636.0,500.0,526.0,42.0,8522.0,22632.0,8717.0,14907.0,636.0,44.0
2,Algeria,DZA,15685.0,86914.0,22943.0,7138.0,70.0,24273.0,16702.0,29475.0,...,154666.0,12337.0,6407.0,11066.0,369395.0,168453.0,91927.0,146527.0,27628.0,10492.0
3,American Samoa,ASM,30.0,143.0,69.0,60.0,0.0,120.0,101.0,30.0,...,512.0,0.0,60.0,0.0,164.0,612.0,181.0,341.0,0.0,0.0
4,Andorra,AND,0.0,614.0,137.0,0.0,0.0,0.0,15.0,0.0,...,292.0,0.0,0.0,0.0,259.0,838.0,283.0,560.0,0.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,World,OWID_WRL,10530812.0,29785753.0,7183831.0,13799126.0,25351326.0,10307437.0,12778623.0,7732400.0,...,28930714.0,2602234.0,12038586.0,336547.0,36317087.0,104644807.0,37499959.0,65674474.0,3605745.0,3786122.0
213,Yemen,YEM,21095.0,31045.0,7188.0,68939.0,143463.0,27994.0,17918.0,53611.0,...,52119.0,12561.0,66731.0,8776.0,278327.0,126525.0,64136.0,111536.0,23871.0,26532.0
214,Yugoslavia,OWID_YGS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,113.0,0.0,0.0,0.0,0.0,0.0,0.0
215,Zambia,ZMB,98886.0,13473.0,4054.0,95913.0,205529.0,12809.0,30065.0,28395.0,...,41751.0,9056.0,92915.0,21.0,56976.0,59173.0,100581.0,147640.0,9476.0,8846.0
216,Zimbabwe,ZWE,41238.0,20017.0,5764.0,66723.0,118728.0,18169.0,32741.0,29802.0,...,49952.0,9113.0,65942.0,27.0,67207.0,71774.0,55027.0,108691.0,14718.0,3778.0

In [19]:
lst = list(df)


for i in range(len(lst)):
    e = lst[i]
    if 'Deaths -' in e:
        e = re.sub(r'Deaths - ([^-]+).*', r'\1', e )
        lst[i] = str(e)
    

#lst[lst.index('Number of executions (Amnesty International)')] = 'Executions'
lst[lst.index('Terrorism (deaths)')] = 'Terrorism'
        
df.columns = lst

df.head()

,Entity,Code,Meningitis,Alzheimer's disease and other dementias,Parkinson's disease,Nutritional deficiencies,Malaria,Drowning,Interpersonal violence,Maternal disorders,...,Chronic kidney disease,Poisonings,Protein,Terrorism,Road injuries,Chronic respiratory diseases,Cirrhosis and other chronic liver diseases,Digestive diseases,"Fire, heat, and hot substances",Acute hepatitis
0,Afghanistan,AFG,78666.0,41998.0,13397.0,71453.0,13924.0,56536.0,108228.0,129621.0,...,134676.0,14530.0,70163.0,39193.0,208331.0,209857.0,98419.0,186959.0,13559.0,98108.0
1,Albania,ALB,1323.0,16549.0,4491.0,569.0,0.0,2397.0,5242.0,246.0,...,7636.0,500.0,526.0,42.0,8522.0,22632.0,8717.0,14907.0,636.0,44.0
2,Algeria,DZA,15685.0,86914.0,22943.0,7138.0,70.0,24273.0,16702.0,29475.0,...,154666.0,12337.0,6407.0,11066.0,369395.0,168453.0,91927.0,146527.0,27628.0,10492.0
3,American Samoa,ASM,30.0,143.0,69.0,60.0,0.0,120.0,101.0,30.0,...,512.0,0.0,60.0,0.0,164.0,612.0,181.0,341.0,0.0,0.0
4,Andorra,AND,0.0,614.0,137.0,0.0,0.0,0.0,15.0,0.0,...,292.0,0.0,0.0,0.0,259.0,838.0,283.0,560.0,0.0,30.0

In [20]:
#df = df.groupby('Entity', 'Code').sum().reset_index()

df['Total'] = df.sum(axis=1).astype(int)

for i in range(2, len(lst)):
    df[lst[i]] = df[lst[i]].astype(int)

/tmp/ipykernel_67983/4060327480.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df['Total'] = df.sum(axis=1).astype(int)

In [21]:
df['Total'] = df.sum(axis=1)

/tmp/ipykernel_67983/2759960331.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df['Total'] = df.sum(axis=1)

In [22]:
df.dtypes

Entity                                         object
Code                                           object
Meningitis                                      int64
Alzheimer's disease and other dementias         int64
Parkinson's disease                             int64
Nutritional deficiencies                        int64
Malaria                                         int64
Drowning                                        int64
Interpersonal violence                          int64
Maternal disorders                              int64
HIV/AIDS                                        int64
Drug use disorders                              int64
Tuberculosis                                    int64
Cardiovascular diseases                         int64
Lower respiratory infections                    int64
Neonatal disorders                              int64
Alcohol use disorders                           int64
Self                                            int64
Exposure to forces of nature                    int64
Diarrheal diseases                              int64
Environmental heat and cold exposure            int64
Neoplasms                                       int64
Conflict and terrorism                          int64
Diabetes mellitus                               int64
Chronic kidney disease                          int64
Poisonings                                      int64
Protein                                         int64
Terrorism                                       int64
Road injuries                                   int64
Chronic respiratory diseases                    int64
Cirrhosis and other chronic liver diseases      int64
Digestive diseases                              int64
Fire, heat, and hot substances                  int64
Acute hepatitis                                 int64
Total                                           int64
dtype: object

In [23]:
df = df.drop(df[df.Entity == 'World'].index)

df.to_csv('dataset.csv')

In [24]:
df['Total'].idxmax()

37

In [25]:
df.iloc[212]

Entity                                           Yemen
Code                                               YEM
Meningitis                                       21095
Alzheimer's disease and other dementias          31045
Parkinson's disease                               7188
Nutritional deficiencies                         68939
Malaria                                         143463
Drowning                                         27994
Interpersonal violence                           17918
Maternal disorders                               53611
HIV/AIDS                                          6276
Drug use disorders                                3718
Tuberculosis                                     32460
Cardiovascular diseases                        1110837
Lower respiratory infections                    259044
Neonatal disorders                              729558
Alcohol use disorders                             1590
Self                                             29882
Exposure to forces of nature                      1131
Diarrheal diseases                              419051
Environmental heat and cold exposure              1049
Neoplasms                                       234015
Conflict and terrorism                           95610
Diabetes mellitus                                30812
Chronic kidney disease                           52119
Poisonings                                       12561
Protein                                          66731
Terrorism                                         8776
Road injuries                                   278327
Chronic respiratory diseases                    126525
Cirrhosis and other chronic liver diseases       64136
Digestive diseases                              111536
Fire, heat, and hot substances                   23871
Acute hepatitis                                  26532
Total                                          8194800
Name: 213, dtype: object

In [26]:
df[df['Entity'] == 'France']

,Entity,Code,Meningitis,Alzheimer's disease and other dementias,Parkinson's disease,Nutritional deficiencies,Malaria,Drowning,Interpersonal violence,Maternal disorders,...,Poisonings,Protein,Terrorism,Road injuries,Chronic respiratory diseases,Cirrhosis and other chronic liver diseases,Digestive diseases,"Fire, heat, and hot substances",Acute hepatitis,Total
64,France,FRA,8975,882954,180197,103810,0,31279,21575,2301,...,6253,99271,344,217006,607771,357490,839800,24380,754,30188252